/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchesRouteImport } from './routes/watches'
import { Route as SunglassesRouteImport } from './routes/sunglasses'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as OpticalRouteImport } from './routes/optical'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'

const WatchesRoute = WatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const SunglassesRoute = SunglassesRouteImport.update({
  id: '/sunglasses',
  path: '/sunglasses',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const OpticalRoute = OpticalRouteImport.update({
  id: '/optical',
  path: '/optical',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/optical': typeof OpticalRoute
  '/perfumes': typeof PerfumesRoute
  '/sunglasses': typeof SunglassesRoute
  '/watches': typeof WatchesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/optical': typeof OpticalRoute
  '/perfumes': typeof PerfumesRoute
  '/sunglasses': typeof SunglassesRoute
  '/watches': typeof WatchesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/optical': typeof OpticalRoute
  '/perfumes': typeof PerfumesRoute
  '/sunglasses': typeof SunglassesRoute
  '/watches': typeof WatchesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/optical'
    | '/perfumes'
    | '/sunglasses'
    | '/watches'
    | '/studio/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/optical'
    | '/perfumes'
    | '/sunglasses'
    | '/watches'
    | '/studio/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/optical'
    | '/perfumes'
    | '/sunglasses'
    | '/watches'
    | '/studio/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OpticalRoute: typeof OpticalRoute
  PerfumesRoute: typeof PerfumesRoute
  SunglassesRoute: typeof SunglassesRoute
  WatchesRoute: typeof WatchesRoute
  StudioSplatRoute: typeof StudioSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunglasses': {
      id: '/sunglasses'
      path: '/sunglasses'
      fullPath: '/sunglasses'
      preLoaderRoute: typeof SunglassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optical': {
      id: '/optical'
      path: '/optical'
      fullPath: '/optical'
      preLoaderRoute: typeof OpticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OpticalRoute: OpticalRoute,
  PerfumesRoute: PerfumesRoute,
  SunglassesRoute: SunglassesRoute,
  WatchesRoute: WatchesRoute,
  StudioSplatRoute: StudioSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
